### ISSUE TITLE
EW Update?

### ISSUE THREAD

**Issue by Nillinn** [Eternita-S/EnmityHp#2]
Hello, do you plan on updating this for Endwalker?

**Comment by Eternita-S** [comment]
Hello, should be updated now!

**Comment by Nillinn** [comment]
![image](https://user-images.githubusercontent.com/94562218/149344870-99a0bcce-e2cf-445e-a623-d706fc1d93e3.png)
I think something went wrong with the upload. It never got updated to me. Should I try re-adding the repo?

**Comment by Eternita-S** [comment]
Forgot to update api version in plugin repo, it should be fine now (game restart might be needed though). 
You can use `/xldev` - plugins - load all api levels in meantime if you want to use it without restart
