### ISSUE TITLE
HP stuck at 100%

### ISSUE THREAD

**Issue by Nillinn** [Eternita-S/EnmityHp#3]
Screenshot taken in Void Ark alliance raid. Happening to every enemy in the enmity list after the Endwalker update
![image](https://user-images.githubusercontent.com/94562218/149412685-80c532c8-69e4-4680-a390-fa5ad3ab4c36.png)

**Comment by KGruson** [comment]
Can confirm
![image](https://user-images.githubusercontent.com/89548146/149511570-784319f6-54b4-4e89-9ece-a87f2f3a1467.png)

**Comment by Eternita-S** [comment]
It should be fixed now in update

**Comment by KGruson** [comment]
yep, fixed
