### ISSUE TITLE
Automatic disable while in PVP

### ISSUE THREAD

**Issue by joesh1n** [Eternita-S/EnmityHp#4]
Is there any chance that the plugin does not show hp while in PVP? 
There's no enmity list but it's still showing the HP percentages.

**Comment by Eternita-S** [comment]
Hello! Did you meant that you want the plugin to be disabled in PVP?

**Comment by joesh1n** [comment]
> Hello! Did you meant that you want the plugin to be disabled in PVP?

Hi, yes that is what I meant!

**Comment by Eternita-S** [comment]
I will add this feature in next version of plugin

**Comment by joesh1n** [comment]
Sounds good. Thank you!
